import { ConcertSlide, EventItem, ArtistItem } from './types';
import saliyahBanner from './assets/images/regenerated_image_1782152554930.jpg';
import saliyahAvatar from './assets/images/regenerated_image_1782152555989.jpg';

export const INITIAL_CONCERTS: ConcertSlide[] = [
  {
    id: 'c1',
    day: '19',
    month: 'MAY 2025',
    ordinal: 'TH',
    time: '04 PM',
    location: 'LOS ANGELES, CALI',
    venue: 'STAPLES, CENTER',
    ticketType: 'GENERAL ADMISSION'
  },
  {
    id: 'c2',
    day: '30',
    month: 'MARCH 2025',
    ordinal: 'TH',
    time: '19 PM',
    location: 'AUSTIN, TEXAS',
    venue: 'KIA FORUM',
    ticketType: 'INDIVIDUAL VIP BACKSTAGE'
  },
  {
    id: 'c3',
    day: '15',
    month: 'APRIL 2025',
    ordinal: 'TH',
    time: '20 PM',
    location: 'AUSTIN, TEXAS',
    venue: 'KIA FORUM',
    ticketType: 'INDIVIDUAL VIP BACKSTAGE'
  },
  {
    id: 'c4',
    day: '24',
    month: 'APRIL 2025',
    ordinal: 'TH',
    time: '21 PM',
    location: 'MIAMI, FLORIDA',
    venue: 'FTX ARENA',
    ticketType: 'INDIVIDUAL PREMIUM SUITE'
  }
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'e1',
    title: 'Ubuntu Festival',
    month: 'DEC',
    day: '09',
    description: 'A celebration of unity through music, dance, and culture. Join top African acts live on stage.',
    location: 'Pinnacle Mall, Lusaka',
    category: 'Festival',
    subcategories: ['Dance', 'Food'],
    imageUrl: 'https://framerusercontent.com/images/x0JxuHIiPplVGFO6uYnTagZHrk.jpg',
    artistId: 'a1',
    ticketLimit: 1200,
    ticketsSold: 840,
    hasEarlyBird: true,
    earlyBirdPrice: 'K150',
    generalPrice: 'K250',
    vipPrice: 'K650',
    ticketLink: 'https://www.quicket.co.zm/events/ubuntu-festival-2025',
    alternativeDates: [
      { id: 'as1', month: 'DEC', day: '10', time: 'Sat 8:00PM', status: 'AVAILABLE' },
      { id: 'as2', month: 'DEC', day: '11', time: 'Sun 5:00PM', status: 'STANDBY' }
    ]
  },
  {
    id: 'e2',
    title: 'Coca Cola Festival',
    month: 'FEB',
    day: '27',
    description: 'A massive music festival sponsored by Coca Cola featuring top DJs and pop acts across Africa.',
    location: 'Pinnacle Mall, Lusaka',
    category: 'Festival',
    subcategories: ['Food', 'Dance'],
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80',
    artistId: 'a2',
    ticketLimit: 2500,
    ticketsSold: 1120,
    hasEarlyBird: true,
    earlyBirdPrice: 'K100',
    generalPrice: 'K200',
    vipPrice: 'K500',
    ticketLink: 'https://coke-music-fest.co.zm',
    alternativeDates: [
      { id: 'as3', month: 'FEB', day: '28', time: 'Sun 3:00PM', status: 'AVAILABLE' }
    ]
  },
  {
    id: 'e3',
    title: 'Spring Vibes Festival',
    month: 'NOV',
    day: '12',
    description: 'Celebrate the change of season with live bands, fashion shows, and outdoor fun.',
    location: 'Showgrounds, Lusaka',
    category: 'Festival',
    subcategories: ['Fashion', 'Food'],
    imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=600&q=80',
    artistId: 'a1',
    ticketLimit: 800,
    ticketsSold: 650,
    hasEarlyBird: false,
    generalPrice: 'K150',
    vipPrice: 'K400',
    alternativeDates: []
  },
  {
    id: 'e4',
    title: 'Lusaka Nights Concert',
    month: 'MAR',
    day: '05',
    description: 'Experience electrifying performances under the stars — from hip hop to amapiano vibes.',
    location: 'East Park Mall, Lusaka',
    category: 'Concert',
    subcategories: ['Hip-Hop', 'Dance'],
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80',
    artistId: 'a3',
    ticketLimit: 1500,
    ticketsSold: 1475,
    hasEarlyBird: true,
    earlyBirdPrice: 'K200',
    generalPrice: 'K300',
    vipPrice: 'K800',
    ticketLink: 'https://lusaka-nights.co.zm',
    alternativeDates: [
      { id: 'as4', month: 'MAR', day: '06', time: 'Thu 8:00PM', status: 'SOLD OUT' }
    ]
  },
  {
    id: 'e5',
    title: 'DJ Takeover Party',
    month: 'JUN',
    day: '02',
    description: 'Dance all night as Zambia’s hottest DJs bring amapiano, afrobeats, and house to the main stage.',
    location: 'Club Elixir, Lusaka',
    category: 'Concert',
    subcategories: ['Dance'],
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80',
    artistId: 'a4',
    ticketLimit: 400,
    ticketsSold: 390,
    hasEarlyBird: true,
    earlyBirdPrice: 'K120',
    generalPrice: 'K220',
    vipPrice: 'K500',
    alternativeDates: []
  },
  {
    id: 'e6',
    title: 'Zed Sports Fest',
    month: 'APR',
    day: '19',
    description: 'Where football passion meets live music. Watch exhibition matches and party with DJs afterward.',
    location: 'National Heroes Stadium, Lusaka',
    category: 'Sports',
    subcategories: ['Food', 'Dance'],
    imageUrl: 'https://framerusercontent.com/images/9Jt8jKzYDoRNpB2U0PtgiytsJc.jpg?scale-down-to=1024',
    artistId: 'a3',
    ticketLimit: 5000,
    ticketsSold: 3200,
    hasEarlyBird: false,
    generalPrice: 'K50',
    vipPrice: 'K300',
    alternativeDates: [
      { id: 'as5', month: 'APR', day: '20', time: 'Sun 10:00AM', status: 'AVAILABLE' }
    ]
  },
  {
    id: 'e7',
    title: 'Taste of Zambia',
    month: 'JUL',
    day: '23',
    description: 'Food, fashion, and tradition collide — sample cuisines, shop local brands, and enjoy live cooking shows.',
    location: 'ZAMCOM Lodge, Lusaka',
    category: 'Lifestyle',
    subcategories: ['Food', 'Fashion'],
    imageUrl: 'https://framerusercontent.com/images/0vAlMjrPgF7j1LZ4gA7p7nStaM.jpg?scale-down-to=1024',
    artistId: 'a5',
    ticketLimit: 600,
    ticketsSold: 180,
    hasEarlyBird: true,
    earlyBirdPrice: 'K100',
    generalPrice: 'K180',
    vipPrice: 'K450',
    alternativeDates: [
      { id: 'as6', month: 'JUL', day: '24', time: 'Sat 12:00PM', status: 'AVAILABLE' }
    ]
  },
  {
    id: 'e8',
    title: 'Art & Soul Expo',
    month: 'AUG',
    day: '01',
    description: 'A weekend of creativity featuring Zambian visual artists, live painting, and cultural showcases.',
    location: 'Lusaka National Museum, Lusaka',
    category: 'Arts',
    subcategories: ['Fashion'],
    imageUrl: 'https://framerusercontent.com/images/JMvjL5ECoAhua4BsFsVNKZUwtc.jpg',
    artistId: 'a7',
    ticketLimit: 300,
    ticketsSold: 120,
    hasEarlyBird: false,
    generalPrice: 'K100',
    vipPrice: 'K250',
    alternativeDates: []
  },
  {
    id: 'e9',
    title: 'Afrobeat Nation',
    month: 'AUG',
    day: '18',
    description: 'A mega concert dedicated to the best of afrobeats, dancehall, and hip-hop.',
    location: 'Woodlands Stadium, Lusaka',
    category: 'Concert',
    subcategories: ['Hip-Hop', 'Dance'],
    imageUrl: 'https://framerusercontent.com/images/tjbRA074Biebffu8nIkWLAYWKA.jpg',
    artistId: 'a1',
    ticketLimit: 3000,
    ticketsSold: 1980,
    hasEarlyBird: true,
    earlyBirdPrice: 'K150',
    generalPrice: 'K250',
    vipPrice: 'K700',
    alternativeDates: []
  },
  {
    id: 'e10',
    title: 'Zambia New Year Countdown',
    month: 'DEC',
    day: '31',
    description: 'Ring in the new year with fireworks, live music, and unforgettable performances.',
    location: 'Polo Club, Lusaka',
    category: 'Lifestyle',
    subcategories: ['Dance', 'Food'],
    imageUrl: 'https://framerusercontent.com/images/nBzePLgA1hbCrIKUkIpxnq5JmfM.jpg?scale-down-to=1024',
    artistId: 'a9',
    ticketLimit: 4000,
    ticketsSold: 3500,
    hasEarlyBird: true,
    earlyBirdPrice: 'K250',
    generalPrice: 'K400',
    vipPrice: 'K1200',
    alternativeDates: []
  },
  {
    id: 'e11',
    title: 'Theatre Under the Stars',
    month: 'JAN',
    day: '09',
    description: 'An outdoor evening of storytelling, drama, and laughter featuring Zambia’s top theatre groups.',
    location: 'Playhouse Theatre, Lusaka',
    category: 'Arts',
    subcategories: ['Dance'],
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=600&q=80',
    artistId: 'a8',
    ticketLimit: 350,
    ticketsSold: 110,
    hasEarlyBird: false,
    generalPrice: 'K80',
    vipPrice: 'K200',
    alternativeDates: []
  }
];

export const ARTISTS: ArtistItem[] = [
  {
    id: 'a1',
    name: 'Cleo Ice Queen',
    slug: 'artist-events-page',
    category: 'Music',
    typeLabel: 'Zambian Rap & Hip-Hop Icon',
    location: 'Lusaka, Pinnacle Mall',
    festivalDate: 'Saturday, April 12, 2025',
    festivalTime: 'Fri 7:30PM',
    avatarUrl: saliyahAvatar,
    bannerUrl: saliyahBanner,
    avatarPosition: 'center 20%',
    bannerPosition: 'center 30%',
    bio: 'Multi-award winning Zambian rap monarch known for her powerful lyrics, fashion-forward visual styles, and continuous cultural influence. Cleo Ice Queen remains a leading headlining act across southern Africa, delivering high-octane performances blending traditional flow and contemporary hip-hop rhythms.',
    specialties: ['Hip-Hop', 'Rap', 'Afro-Fusion', 'Fashion']
  },
  {
    id: 'a2',
    name: 'Kunkeyani Tha Jedi',
    slug: 'artist-events-page-2',
    category: 'Music',
    typeLabel: 'Lyricist & Street Ambassador',
    location: 'Showgrounds Main Stage, Lusaka',
    festivalDate: 'Saturday, April 12, 2025',
    festivalTime: 'Sat 8:00PM',
    avatarUrl: 'https://framerusercontent.com/images/4KwGulfVE58DNM8WLf5NHvsQ.jpg',
    bannerUrl: 'https://framerusercontent.com/images/pftyzBB67d2TZSnCpKHzYnCg2k.png',
    avatarPosition: 'center 15%',
    bannerPosition: 'center 20%',
    bio: 'Zambia’s very own lyrical master who brings unmatched poetic street commentary, infectious raw flows, and stellar stage presence. Known for storytelling and powerful social narratives, Kunkeyani Tha Jedi is set to deliver an incredible performance blending Lusaka heritage with modern amapiano rhythms.',
    specialties: ['Rap', 'Hip-Hop', 'Lyrics', 'Amapiano']
  },
  {
    id: 'a3',
    name: 'Chef 187',
    slug: 'artist-events-page',
    category: 'Music',
    typeLabel: 'Zambian Lyrical Hip-Hop Legend',
    location: 'Woodlands Stadium, Lusaka',
    festivalDate: 'Friday, June 20, 2025',
    festivalTime: 'Fri 9:00PM',
    avatarUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    avatarPosition: 'center 20%',
    bannerPosition: 'center 20%',
    bio: 'The undisputed king of Zambian Bemba lyrical rap. Chef 187 packs stadiums with his sharp wit, high-energy delivery, and continuous chart-topping catalog. His shows are unforgettable celebrations of Zambian youth culture and rhythm.',
    specialties: ['Hip-Hop', 'Bemba Rap', 'Afrobeats']
  },
  {
    id: 'a4',
    name: 'El Mukuka',
    slug: 'artist-events-page-2',
    category: 'Music',
    typeLabel: 'House Music DJ & Producer',
    location: 'Polo Club, Lusaka',
    festivalDate: 'Saturday, July 12, 2025',
    festivalTime: 'Sat 5:30PM',
    avatarUrl: 'https://images.unsplash.com/photo-1516873240891-4bf014598ab4?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1200&q=80',
    avatarPosition: 'center 15%',
    bannerPosition: 'center 30%',
    bio: 'Zambia’s premiere electronic music ambassador. El Mukuka is famous for fusing high-spirited organic African folk melodies with progressive deep house beats, spinning a warm aesthetic that dominates dance floors.',
    specialties: ['Deep House', 'Afro-House', 'Electronic']
  },
  {
    id: 'a5',
    name: 'Zambiate Bites',
    slug: 'artist-events-page',
    category: 'Food',
    typeLabel: 'Artisanal Caterer & Culinary Studio',
    location: 'Pinnacle Mall Food Court, Lusaka',
    festivalDate: 'Sunday, May 18, 2025',
    festivalTime: 'Sun 12:00PM',
    avatarUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    avatarPosition: 'center',
    bannerPosition: 'center',
    bio: 'Zambiate Bites is an artisanal organic culinary kitchen focusing on elevates local ingredients into high-end fine dining formats. Famous for their organic cassava leaf dressings, customized Nshima bars, and grilled wild game skewers.',
    specialties: ['Catering', 'Zambian Gastronomy', 'Nshima Bowls', 'African Fusion']
  },
  {
    id: 'a6',
    name: 'Lusaka Smokehouse & Grill',
    slug: 'artist-events-page-2',
    category: 'Food',
    typeLabel: 'Traditional Pitmasters & Smokehouse',
    location: 'East Park Mall Lawn, Lusaka',
    festivalDate: 'Saturday, August 9, 2025',
    festivalTime: 'Sat 11:30AM',
    avatarUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1200&q=80',
    avatarPosition: 'center',
    bannerPosition: 'center',
    bio: 'Specializing in slow wood-smoked meats and pork ribs basted with a special regional Zambian honey and local chilli wood fires. Famous for keeping it traditional yet premium at open-air food festivals.',
    specialties: ['BBQ & Smoke', 'Gourmet Grill', 'Chilli Rubs']
  },
  {
    id: 'a7',
    name: 'The Village Kitchen',
    slug: 'artist-events-page',
    category: 'Food',
    typeLabel: 'Indigenous Charcoal Kitchen',
    location: 'ZAMCOM Lodge Garden, Lusaka',
    festivalDate: 'Thursday, November 20, 2025',
    festivalTime: 'Thu 1:00PM',
    avatarUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80',
    avatarPosition: 'center',
    bannerPosition: 'center',
    bio: 'The Village Kitchen preserves Zambia’s culinary lineage using organic, wood-fire clay pots. Savor genuine clay-pot cooked native pumpkin leaves (Chibwabwa) and local free-range chicken served with stone-ground premium grains.',
    specialties: ['Indigenous Nshima', 'Chibwabwa', 'Mabisi sour milk', 'Clay Pot Cookery']
  },
  {
    id: 'a8',
    name: 'Lusaka Culinary Expo',
    slug: 'artist-events-page-2',
    category: 'Festival',
    typeLabel: 'Gourmet Festival Organizers',
    location: 'Polo Club Gardens, Lusaka',
    festivalDate: 'Saturday, September 13, 2025',
    festivalTime: 'Sat 10:00AM',
    avatarUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=1200&q=80',
    avatarPosition: 'center',
    bannerPosition: 'center',
    bio: 'The crown-jewel of food and hospitality showcase events in Lusaka. Providing local artisanal startups with a massive platform to demo recipes, host live tasting programs, and run international masterclasses.',
    specialties: ['Food Expositions', 'Wine Pairings', 'Culinary Workshops']
  },
  {
    id: 'a9',
    name: 'Oktoberfest Lusaka',
    slug: 'artist-events-page',
    category: 'Festival',
    typeLabel: 'Outdoor Lifestyle Festival Council',
    location: 'Showgrounds Arena, Lusaka',
    festivalDate: 'Saturday, October 11, 2025',
    festivalTime: 'Sat 12:00PM',
    avatarUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80',
    avatarPosition: 'center',
    bannerPosition: 'center font-medium',
    bio: 'Lusaka’s premier beer, food, and music garden experience. An annual outdoor event that holds thousands of fans, live bands, and craft tasting hubs for a beautiful, premium, safe experience.',
    specialties: ['Biergartens', 'Craft Markets', 'Live Band Concerts']
  }
];
